apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutriflow-backend
  namespace: nutriflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutriflow-backend
  template:
    metadata:
      labels:
        app: nutriflow-backend
    spec:
      containers:
        - name: backend
          image: 509305826826.dkr.ecr.eu-north-1.amazonaws.com/nutriflow-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: nutriflow-backend-secret
