apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutriflow-frontend
  namespace: nutriflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutriflow-frontend
  template:
    metadata:
      labels:
        app: nutriflow-frontend
    spec:
      containers:
        - name: frontend
          image: 509305826826.dkr.ecr.eu-north-1.amazonaws.com/nutriflow-frontend:latest
          ports:
            - containerPort: 80
